### ISSUE TITLE
Regarding HA-Proxy scenario.!

### ISSUE THREAD

**Issue by ShobhitGoel95** [Axway-API-Management-Plus/Installation-configuration-by-SCRIPT--API-Gateway#1]
Hey Altaf , 
Thanks for the script.
But I have a question like when we want to use the scenario where : we want 2 front nodes and 2 back nodes? In that case what changes we need to do in "installationDetails.txt" file?
I guess we need to change these 2 factors:
- replicationfactor=2 (instead of 1)
- instancename=<anything different from first one> 

Please let me know if am doing it right or wrong?

**Comment by Altaf-Axway** [comment]
the replicationfactor is for the cassandra cluster that can be set to 1 or 3 depending on your cassandra cluster size

**Comment by Altaf-Axway** [comment]
when your cluster only have 1 cassandra node the set the replicationfactor to 1 if the cassandra nodes are 3 then replicationfactor  can se set to 3
